# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'guest-list' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for guest-list
  pod 'Firebase/Firestore', '6.10.0' 

end
